### ISSUE TITLE
Test socket.io

### ISSUE THREAD

**Issue by saitejar** [saitejar/colabedit#5]
send character stream via socket.io from client to server.

**Comment by saitejar** [comment]
Thanks prashanth, push in the code for it after making necessary modifications.

**Comment by Prashanth-Billa** [comment]
unique session identifier now working for each client..... pushed code.. run and check console

**Comment by saitejar** [comment]
wow.. superb..

**Comment by saitejar** [comment]
are you able to also set the id ?

**Comment by Prashanth-Billa** [comment]
not really sure.... the id is set by the internal library... better not to modify it

**Comment by prakul** [comment]
Why is this a public repo? Shouldnt we be doing our work privately and then
after submission make it public ?
